import json

vocab_data = {
    "N5": [
        {"word": "行く", "reading": "いく", "meaning": "가다", "exJp": "明日、学校へ行く。", "exKo": "내일, 학교에 간다."},
        {"word": "食べる", "reading": "たべる", "meaning": "먹다", "exJp": "朝ごはんを食べる。", "exKo": "아침밥을 먹는다."},
        {"word": "飲む", "reading": "のむ", "meaning": "마시다", "exJp": "冷たい水を飲む。", "exKo": "차가운 물을 마신다."},
        {"word": "水", "reading": "みず", "meaning": "물", "exJp": "コップに水を入れる。", "exKo": "컵에 물을 넣는다."},
        {"word": "本", "reading": "ほん", "meaning": "책", "exJp": "図書館で本を借りる。", "exKo": "도서관에서 책을 빌린다."},
        {"word": "猫", "reading": "ねこ", "meaning": "고양이", "exJp": "白い猫が寝ている。", "exKo": "하얀 고양이가 자고 있다."},
        {"word": "犬", "reading": "いぬ", "meaning": "개", "exJp": "公園で犬と遊ぶ。", "exKo": "공원에서 개와 논다."},
        {"word": "人", "reading": "ひと", "meaning": "사람", "exJp": "あの人は誰ですか。", "exKo": "저 사람은 누구입니까?"},
        {"word": "見る", "reading": "みる", "meaning": "보다", "exJp": "面白い映画を見る。", "exKo": "재미있는 영화를 본다."},
        {"word": "寝る", "reading": "ねる", "meaning": "자다", "exJp": "夜早く寝る。", "exKo": "밤에 일찍 잔다."},
        {"word": "起きる", "reading": "おきる", "meaning": "일어나다", "exJp": "朝7時に起きる。", "exKo": "아침 7시에 일어난다."},
        {"word": "車", "reading": "くるま", "meaning": "자동차", "exJp": "車に乗って出かける。", "exKo": "차를 타고 외출한다."},
        {"word": "先生", "reading": "せんせい", "meaning": "선생님", "exJp": "先生に質問する。", "exKo": "선생님에게 질문한다."},
        {"word": "学校", "reading": "がっこう", "meaning": "학교", "exJp": "学校で勉強する。", "exKo": "학교에서 공부한다."},
        {"word": "買う", "reading": "かう", "meaning": "사다", "exJp": "新しい服を買う。", "exKo": "새 옷을 산다."},
        {"word": "大きい", "reading": "おおきい", "meaning": "크다", "exJp": "とても大きい家だ。", "exKo": "매우 큰 집이다."},
        {"word": "小さい", "reading": "ちいさい", "meaning": "작다", "exJp": "小さい声で話す。", "exKo": "작은 목소리로 말한다."},
        {"word": "高い", "reading": "たかい", "meaning": "높다, 비싸다", "exJp": "この鞄は高い。", "exKo": "이 가방은 비싸다."},
        {"word": "安い", "reading": "やすい", "meaning": "싸다", "exJp": "安い店を探す。", "exKo": "싼 가게를 찾는다."},
        {"word": "新しい", "reading": "あたらしい", "meaning": "새롭다", "exJp": "新しい靴を履く。", "exKo": "새 신발을 신는다."},
        {"word": "古い", "reading": "ふるい", "meaning": "오래되다", "exJp": "古い建物を壊す。", "exKo": "오래된 건물을 부순다."},
        {"word": "良い", "reading": "よい", "meaning": "좋다", "exJp": "天気が良くて気持ちいい。", "exKo": "날씨가 좋아서 기분이 좋다."},
        {"word": "悪い", "reading": "わるい", "meaning": "나쁘다", "exJp": "今日は気分が悪い。", "exKo": "오늘은 기분이 나쁘다."},
        {"word": "赤", "reading": "あか", "meaning": "빨강", "exJp": "赤いリンゴを食べる。", "exKo": "빨간 사과를 먹는다."},
        {"word": "青", "reading": "あお", "meaning": "파랑", "exJp": "青い空が広がる。", "exKo": "파란 하늘이 펼쳐진다."},
        {"word": "白", "reading": "しろ", "meaning": "하양", "exJp": "白い雲が浮かぶ。", "exKo": "하얀 구름이 떠오른다."},
        {"word": "黒", "reading": "くろ", "meaning": "검정", "exJp": "黒いペンで書く。", "exKo": "검은 펜으로 쓴다."},
        {"word": "上", "reading": "うえ", "meaning": "위", "exJp": "机の上に本がある。", "exKo": "책상 위에 책이 있다."},
        {"word": "下", "reading": "した", "meaning": "아래", "exJp": "椅子の下に猫がいる。", "exKo": "의자 아래에 고양이가 있다."},
        {"word": "前", "reading": "まえ", "meaning": "앞", "exJp": "駅の前で待つ。", "exKo": "역 앞에서 기다린다."},
        {"word": "右", "reading": "みぎ", "meaning": "오른쪽", "exJp": "右に曲がる。", "exKo": "오른쪽으로 돈다."},
        {"word": "左", "reading": "ひだり", "meaning": "왼쪽", "exJp": "左手で書く。", "exKo": "왼손으로 쓴다."},
        {"word": "時間", "reading": "じかん", "meaning": "시간", "exJp": "時間がありません。", "exKo": "시간이 없습니다."},
        {"word": "お金", "reading": "おかね", "meaning": "돈", "exJp": "お金を払う。", "exKo": "돈을 지불한다."},
        {"word": "友達", "reading": "ともだち", "meaning": "친구", "exJp": "友達と遊ぶ。", "exKo": "친구와 논다."},
        {"word": "家族", "reading": "かぞく", "meaning": "가족", "exJp": "家族で旅行する。", "exKo": "가족과 여행한다."},
        {"word": "名前", "reading": "なまえ", "meaning": "이름", "exJp": "名前を書く。", "exKo": "이름을 쓴다."},
        {"word": "話す", "reading": "はなす", "meaning": "말하다", "exJp": "日本語で話す。", "exKo": "일본어로 말한다."},
        {"word": "聞く", "reading": "きく", "meaning": "듣다", "exJp": "音楽を聞く。", "exKo": "음악을 듣는다."},
        {"word": "書く", "reading": "かく", "meaning": "쓰다", "exJp": "手紙を書く。", "exKo": "편지를 쓴다."},
        {"word": "読む", "reading": "よむ", "meaning": "읽다", "exJp": "新聞を読む。", "exKo": "신문을 읽는다."},
        {"word": "来る", "reading": "くる", "meaning": "오다", "exJp": "友達が家に来る。", "exKo": "친구가 집에 온다."},
        {"word": "待つ", "reading": "まつ", "meaning": "기다리다", "exJp": "バスを待つ。", "exKo": "버스를 기다린다."},
        {"word": "休む", "reading": "やすむ", "meaning": "쉬다", "exJp": "疲れたから休む。", "exKo": "피곤해서 쉰다."},
        {"word": "知る", "reading": "しる", "meaning": "알다", "exJp": "あの人を知っている。", "exKo": "저 사람을 안다."},
        {"word": "入る", "reading": "はいる", "meaning": "들어가다", "exJp": "お風呂に入る。", "exKo": "목욕을 한다."},
        {"word": "出る", "reading": "でる", "meaning": "나가다", "exJp": "部屋を出る。", "exKo": "방을 나간다."},
        {"word": "立つ", "reading": "たつ", "meaning": "서다", "exJp": "そこに立つ。", "exKo": "거기에 선다."},
        {"word": "座る", "reading": "すわる", "meaning": "앉다", "exJp": "椅子に座る。", "exKo": "의자에 앉는다."},
        {"word": "終わる", "reading": "おわる", "meaning": "끝나다", "exJp": "授業が終わる。", "exKo": "수업이 끝난다."},
        {"word": "始まる", "reading": "はじまる", "meaning": "시작되다", "exJp": "映画が始まる。", "exKo": "영화가 시작된다."},
        {"word": "会う", "reading": "あう", "meaning": "만나다", "exJp": "駅で友達に会う。", "exKo": "역에서 친구를 만난다."},
        {"word": "作る", "reading": "つくる", "meaning": "만들다", "exJp": "料理を作る。", "exKo": "요리를 만든다."},
        {"word": "使う", "reading": "つかう", "meaning": "사용하다", "exJp": "パソコンを使う。", "exKo": "컴퓨터를 사용한다."},
        {"word": "教える", "reading": "おしえる", "meaning": "가르치다", "exJp": "日本語を教える。", "exKo": "일본어를 가르친다."}
    ],
    "N4": [
        {"word": "都合", "reading": "つごう", "meaning": "사정", "exJp": "明日は都合が悪いです。", "exKo": "내일은 사정이 안 좋습니다."},
        {"word": "約束", "reading": "やくそく", "meaning": "약속", "exJp": "友達と約束をした。", "exKo": "친구와 약속을 했다."},
        {"word": "準備", "reading": "じゅんび", "meaning": "준비", "exJp": "旅行の準備をする。", "exKo": "여행 준비를 한다."},
        {"word": "連絡", "reading": "れんらく", "meaning": "연락", "exJp": "後でまた連絡します。", "exKo": "나중에 다시 연락할게요."},
        {"word": "趣味", "reading": "しゅみ", "meaning": "취미", "exJp": "私の趣味は読書です。", "exKo": "내 취미는 독서입니다."},
        {"word": "説明", "reading": "せつめい", "meaning": "설명", "exJp": "ルールを詳しく説明する。", "exKo": "규칙을 자세히 설명한다."},
        {"word": "相談", "reading": "そうだん", "meaning": "상담", "exJp": "先生に相談する。", "exKo": "선생님과 상담하다."},
        {"word": "経験", "reading": "けいけん", "meaning": "경험", "exJp": "色々な経験をする。", "exKo": "다양한 경험을 하다."},
        {"word": "計画", "reading": "けいかく", "meaning": "계획", "exJp": "計画を立てる。", "exKo": "계획을 세운다."},
        {"word": "案内", "reading": "あんない", "meaning": "안내", "exJp": "町を案内する。", "exKo": "거리를 안내하다."},
        {"word": "紹介", "reading": "しょうかい", "meaning": "소개", "exJp": "自己紹介をします。", "exKo": "자기소개를 하겠습니다."},
        {"word": "予約", "reading": "よやく", "meaning": "예약", "exJp": "レストランを予約する。", "exKo": "레스토랑을 예약하다."},
        {"word": "生産", "reading": "せいさん", "meaning": "생산", "exJp": "新しい車を生産する。", "exKo": "새로운 자동차를 생산하다."},
        {"word": "利用", "reading": "りよう", "meaning": "이용", "exJp": "地下鉄を利用する。", "exKo": "지하철을 이용하다."},
        {"word": "注意", "reading": "ちゅうい", "meaning": "주의", "exJp": "車に注意して歩く。", "exKo": "차를 주의하며 걷다."},
        {"word": "事故", "reading": "じこ", "meaning": "사고", "exJp": "交通事故が起きる。", "exKo": "교통사고가 발생하다."},
        {"word": "安全", "reading": "あんぜん", "meaning": "안전", "exJp": "安全第一で働く。", "exKo": "안전제일로 일하다."},
        {"word": "危険", "reading": "きけん", "meaning": "위험", "exJp": "危険な場所に行かない。", "exKo": "위험한 장소에 가지 않는다."},
        {"word": "失敗", "reading": "しっぱい", "meaning": "실패", "exJp": "テストで失敗する。", "exKo": "시험에서 실패하다."},
        {"word": "成功", "reading": "せいこう", "meaning": "성공", "exJp": "実験が成功する。", "exKo": "실험이 성공하다."},
        {"word": "考える", "reading": "かんがえる", "meaning": "생각하다", "exJp": "よく考える。", "exKo": "잘 생각한다."},
        {"word": "決める", "reading": "きめる", "meaning": "정하다", "exJp": "予定を決める。", "exKo": "예정을 정한다."},
        {"word": "続ける", "reading": "つづける", "meaning": "계속하다", "exJp": "勉強を続ける。", "exKo": "공부를 계속한다."},
        {"word": "見つける", "reading": "みつける", "meaning": "발견하다", "exJp": "鍵を見つける。", "exKo": "열쇠를 찾는다."},
        {"word": "比べる", "reading": "くらべる", "meaning": "비교하다", "exJp": "値段を比べる。", "exKo": "가격을 비교한다."},
        {"word": "飾る", "reading": "かざる", "meaning": "장식하다", "exJp": "部屋を飾る。", "exKo": "방을 장식한다."},
        {"word": "急ぐ", "reading": "いそぐ", "meaning": "서두르다", "exJp": "駅へ急ぐ。", "exKo": "역으로 서두른다."},
        {"word": "間に合う", "reading": "まにあう", "meaning": "시간에 맞다", "exJp": "電車に間に合う。", "exKo": "전철 시간에 맞추다."},
        {"word": "喜ぶ", "reading": "よろこぶ", "meaning": "기뻐하다", "exJp": "プレゼントに喜ぶ。", "exKo": "선물에 기뻐하다."},
        {"word": "怒る", "reading": "おこる", "meaning": "화내다", "exJp": "先生が怒る。", "exKo": "선생님이 화낸다."},
        {"word": "楽しむ", "reading": "たのしむ", "meaning": "즐기다", "exJp": "休日を楽しむ。", "exKo": "휴일을 즐긴다."},
        {"word": "慣れる", "reading": "なれる", "meaning": "익숙해지다", "exJp": "仕事に慣れる。", "exKo": "일에 익숙해진다."},
        {"word": "変わる", "reading": "かわる", "meaning": "바뀌다", "exJp": "季節が変わる。", "exKo": "계절이 바뀐다."},
        {"word": "集める", "reading": "あつめる", "meaning": "모으다", "exJp": "切手を集める。", "exKo": "우표를 모은다."},
        {"word": "思い出す", "reading": "おもいだす", "meaning": "생각해내다", "exJp": "昔を思い出す。", "exKo": "옛날을 생각해낸다."},
        {"word": "頑張る", "reading": "がんばる", "meaning": "열심히 하다", "exJp": "明日も頑張る。", "exKo": "내일도 열심히 한다."}
    ],
    "N3": [
         {"word": "条件", "reading": "じょうけん", "meaning": "조건", "exJp": "厳しい条件を出す。", "exKo": "엄격한 조건을 내세운다."},
         {"word": "感情", "reading": "かんじょう", "meaning": "감정", "exJp": "自分の感情を抑える。", "exKo": "자신의 감정을 억누른다."},
         {"word": "結果", "reading": "けっか", "meaning": "결과", "exJp": "良い結果が出る。", "exKo": "좋은 결과가 나오다."},
         {"word": "直接", "reading": "ちょくせつ", "meaning": "직접", "exJp": "社長に直接話す。", "exKo": "사장님에게 직접 이야기하다."},
         {"word": "我慢", "reading": "がまん", "meaning": "참음", "exJp": "これ以上我慢できない。", "exKo": "더 이상 참을 수 없다."},
         {"word": "理解", "reading": "りかい", "meaning": "이해", "exJp": "状況をよく理解する。", "exKo": "상황을 잘 이해하다."},
         {"word": "満足", "reading": "まんぞく", "meaning": "만족", "exJp": "結果に満足している。", "exKo": "결과에 만족하고 있다."},
         {"word": "不足", "reading": "ふそく", "meaning": "부족", "exJp": "水が不足している。", "exKo": "물이 부족하다."},
         {"word": "完成", "reading": "かんせい", "meaning": "완성", "exJp": "絵が完成した。", "exKo": "그림이 완성되었다."},
         {"word": "発見", "reading": "はっけん", "meaning": "발견", "exJp": "新しい星を発見する。", "exKo": "새로운 별을 발견하다."},
         {"word": "発明", "reading": "はつめい", "meaning": "발명", "exJp": "電話を発明した人。", "exKo": "전화를 발명한 사람."},
         {"word": "発展", "reading": "はってん", "meaning": "발전", "exJp": "経済が発展する。", "exKo": "경제가 발전하다."},
         {"word": "努力", "reading": "どりょく", "meaning": "노력", "exJp": "毎日努力を続ける。", "exKo": "매일 노력을 계속하다."},
         {"word": "協力", "reading": "きょうりょく", "meaning": "협력", "exJp": "みんなで協力する。", "exKo": "모두 함께 협력하다."},
         {"word": "競争", "reading": "きょうそう", "meaning": "경쟁", "exJp": "会社間で競争する。", "exKo": "회사 간에 경쟁하다."},
         {"word": "価格", "reading": "かかく", "meaning": "가격", "exJp": "商品の価格が上がる。", "exKo": "상품의 가격이 오르다."},
         {"word": "価値", "reading": "かち", "meaning": "가치", "exJp": "価値のあるものを買う。", "exKo": "가치 있는 것을 산다."},
         {"word": "効果", "reading": "こうか", "meaning": "효과", "exJp": "薬の効果が出る。", "exKo": "약의 효과가 나타나다."},
         {"word": "印象", "reading": "いんしょう", "meaning": "인상", "exJp": "第一印象が大事だ。", "exKo": "첫인상이 중요하다."},
         {"word": "想像", "reading": "そうぞう", "meaning": "상상", "exJp": "未来を想像する。", "exKo": "미래를 상상하다."},
         {"word": "提出", "reading": "ていしゅつ", "meaning": "제출", "exJp": "レポートを提出する。", "exKo": "레포트를 제출한다."},
         {"word": "期待", "reading": "きたい", "meaning": "기대", "exJp": "結果に期待する。", "exKo": "결과를 기대한다."},
         {"word": "感謝", "reading": "かんしゃ", "meaning": "감사", "exJp": "深く感謝する。", "exKo": "깊이 감사하다."},
         {"word": "確認", "reading": "かくにん", "meaning": "확인", "exJp": "事実を確認する。", "exKo": "사실을 확인한다."},
         {"word": "記憶", "reading": "きおく", "meaning": "기억", "exJp": "記憶に残る。", "exKo": "기억에 남는다."},
         {"word": "具体的", "reading": "ぐたいてき", "meaning": "구체적", "exJp": "具体的に説明する。", "exKo": "구체적으로 설명한다."},
         {"word": "可能性", "reading": "かのうせい", "meaning": "가능성", "exJp": "成功の可能性が高い。", "exKo": "성공 가능성이 높다."},
         {"word": "発生", "reading": "はっせい", "meaning": "발생", "exJp": "問題が発生する。", "exKo": "문제가 발생한다."},
         {"word": "提供", "reading": "ていきょう", "meaning": "제공", "exJp": "サービスを提供する。", "exKo": "서비스를 제공한다."},
         {"word": "影響", "reading": "えいきょう", "meaning": "영향", "exJp": "大きな影響を受ける。", "exKo": "큰 영향을 받다."},
         {"word": "責任", "reading": "せきにん", "meaning": "책임", "exJp": "責任を取る。", "exKo": "책임을 진다."}
    ],
    "N2": [
        {"word": "影響", "reading": "えいきょう", "meaning": "영향", "exJp": "環境に影響を与える。", "exKo": "환경에 영향을 주다."},
        {"word": "環境", "reading": "かんきょう", "meaning": "환경", "exJp": "自然環境を守る。", "exKo": "자연 환경을 지키다."},
        {"word": "評価", "reading": "ひょうか", "meaning": "평가", "exJp": "高い評価を受ける。", "exKo": "높은 평가를 받다."},
        {"word": "特徴", "reading": "とくちょう", "meaning": "특징", "exJp": "デザインに特徴がある。", "exKo": "디자인에 특징이 있다."},
        {"word": "現象", "reading": "げんしょう", "meaning": "현상", "exJp": "不思議な現象が起きる。", "exKo": "신비스런 현상이 일어나다."},
        {"word": "対策", "reading": "たいさく", "meaning": "대책", "exJp": "早めの対策が必要だ。", "exKo": "빠른 대책이 필요하다."},
        {"word": "傾向", "reading": "けいこう", "meaning": "경향", "exJp": "最近の若者の傾向。", "exKo": "최근 젊은이들의 경향."},
        {"word": "批判", "reading": "ひはん", "meaning": "비판", "exJp": "政府の政策を批判する。", "exKo": "정부의 정책을 비판하다."},
        {"word": "判断", "reading": "はんだん", "meaning": "판단", "exJp": "自分で判断する。", "exKo": "스스로 판단하다."},
        {"word": "議論", "reading": "ぎろん", "meaning": "의논, 논의", "exJp": "会議で議論する。", "exKo": "회의에서 논의하다."},
        {"word": "比較", "reading": "ひかく", "meaning": "비교", "exJp": "二つの商品を比較する。", "exKo": "두 상품을 비교하다."},
        {"word": "証明", "reading": "しょうめい", "meaning": "증명", "exJp": "自分が正しいと証明する。", "exKo": "자신이 옳다고 증명하다."},
        {"word": "保障", "reading": "ほしょう", "meaning": "보장", "exJp": "安全を保障する。", "exKo": "안전을 보장하다."},
        {"word": "権利", "reading": "けんり", "meaning": "권리", "exJp": "権利を主張する。", "exKo": "권리를 주장하다."},
        {"word": "義務", "reading": "ぎむ", "meaning": "의무", "exJp": "義務を果たす。", "exKo": "의무를 다하다."},
        {"word": "規則", "reading": "きそく", "meaning": "규칙", "exJp": "規則を守る。", "exKo": "규칙을 지키다."},
        {"word": "違反", "reading": "いはん", "meaning": "위반", "exJp": "スピード違反で捕まる。", "exKo": "속도위반으로 잡히다."},
        {"word": "犯罪", "reading": "はんざい", "meaning": "범죄", "exJp": "犯罪を減らす。", "exKo": "범죄를 줄이다."},
        {"word": "被害", "reading": "ひがい", "meaning": "피해", "exJp": "台風の被害に遭う。", "exKo": "태풍 피해를 입다."},
        {"word": "回復", "reading": "かいふく", "meaning": "회복", "exJp": "景気が回復する。", "exKo": "경기가 회복되다."},
        {"word": "慎重", "reading": "しんちょう", "meaning": "신중", "exJp": "慎重に選ぶ。", "exKo": "신중하게 고른다."},
        {"word": "曖昧", "reading": "あいまい", "meaning": "애매", "exJp": "曖昧な返事。", "exKo": "애매한 대답."},
        {"word": "柔軟", "reading": "じゅうなん", "meaning": "유연", "exJp": "柔軟な対応。", "exKo": "유연한 대응."},
        {"word": "豊富", "reading": "ほうふ", "meaning": "풍부", "exJp": "経験が豊富だ。", "exKo": "경험이 풍부하다."},
        {"word": "複雑", "reading": "ふくざつ", "meaning": "복잡", "exJp": "複雑な問題。", "exKo": "복잡한 문제."},
        {"word": "客観的", "reading": "きゃっかんてき", "meaning": "객관적", "exJp": "客観的に見る。", "exKo": "객관적으로 본다."},
        {"word": "主観的", "reading": "しゅかんてき", "meaning": "주관적", "exJp": "主観的な意見。", "exKo": "주관적인 의견."},
        {"word": "相対的", "reading": "そうたいてき", "meaning": "상대적", "exJp": "相対的な価値。", "exKo": "상대적인 가치."},
        {"word": "適切", "reading": "てきせつ", "meaning": "적절", "exJp": "適切な処置。", "exKo": "적절한 처치."},
        {"word": "妥当", "reading": "だとう", "meaning": "타당", "exJp": "妥当な判断。", "exKo": "타당한 판단."}
    ],
    "N1": [
        {"word": "妥協", "reading": "だきょう", "meaning": "타협", "exJp": "絶対に妥協しない。", "exKo": "절대로 타협하지 않는다."},
        {"word": "顕著", "reading": "けんちょ", "meaning": "현저함", "exJp": "傾向が顕著に表れる。", "exKo": "경향이 현저하게 나타난다."},
        {"word": "矛盾", "reading": "むじゅん", "meaning": "모순", "exJp": "彼の発言には矛盾がある。", "exKo": "그의 발언에는 모순이 있다."},
        {"word": "網羅", "reading": "もうら", "meaning": "망라", "exJp": "全分野を網羅する。", "exKo": "모든 분야를 망라하다."},
        {"word": "懸念", "reading": "けねん", "meaning": "우려", "exJp": "将来への懸念を抱く。", "exKo": "장래에 대한 우려를 품다."},
        {"word": "模索", "reading": "もさく", "meaning": "모색", "exJp": "解決策を模索する。", "exKo": "해결책을 모색하다."},
        {"word": "貢献", "reading": "こうけん", "meaning": "공헌", "exJp": "社会に貢献する。", "exKo": "사회에 공헌하다."},
        {"word": "怠る", "reading": "おこたる", "meaning": "게을리하다", "exJp": "義務を怠る。", "exKo": "의무를 게을리하다."},
        {"word": "把握", "reading": "はおく", "meaning": "파악", "exJp": "状況を素早く把握する。", "exKo": "상황을 빠르게 파악하다."},
        {"word": "促す", "reading": "うながす", "meaning": "촉구하다", "exJp": "成長を促す。", "exKo": "성장을 촉구하다."},
        {"word": "免れる", "reading": "まぬがれる", "meaning": "면하다", "exJp": "責任を免れる。", "exKo": "책임을 면하다."},
        {"word": "滞る", "reading": "とどこおる", "meaning": "밀리다, 정체되다", "exJp": "作業が滞る。", "exKo": "작업이 정체되다."},
        {"word": "著しい", "reading": "いちじるしい", "meaning": "눈부시다, 현저하다", "exJp": "著しい進歩を遂げる。", "exKo": "눈부신 진보를 이루다."},
        {"word": "乏しい", "reading": "とぼしい", "meaning": "모자라다, 부족하다", "exJp": "経験が乏しい。", "exKo": "경험이 부족하다."},
        {"word": "偏る", "reading": "かたよる", "meaning": "치우치다", "exJp": "栄養が偏る。", "exKo": "영양이 치우치다."},
        {"word": "覆す", "reading": "くつがえす", "meaning": "뒤집다", "exJp": "常識を覆す。", "exKo": "상식을 뒤집다."},
        {"word": "貫く", "reading": "つらぬく", "meaning": "관철하다", "exJp": "信念を貫く。", "exKo": "신념을 관철하다."},
        {"word": "蓄える", "reading": "たくわえる", "meaning": "저축하다, 비축하다", "exJp": "知識を蓄える。", "exKo": "지식을 비축하다."},
        {"word": "携わる", "reading": "たずさわる", "meaning": "종사하다", "exJp": "教育に携わる。", "exKo": "교육에 종사하다."},
        {"word": "培う", "reading": "つちかう", "meaning": "기르다, 배양하다", "exJp": "能力を培う。", "exKo": "능력을 기르다."},
        {"word": "緻密", "reading": "ちみつ", "meaning": "치밀", "exJp": "緻密な計画。", "exKo": "치밀한 계획."},
        {"word": "漠然", "reading": "ばくぜん", "meaning": "막연", "exJp": "漠然とした不安。", "exKo": "막연한 불안."},
        {"word": "露骨", "reading": "ろこつ", "meaning": "노골", "exJp": "露骨な嫌悪。", "exKo": "노골적인 혐오."},
        {"word": "些细", "reading": "ささい", "meaning": "사소", "exJp": "些細な問題。", "exKo": "사소한 문제."},
        {"word": "頻繁", "reading": "ひんぱん", "meaning": "빈번", "exJp": "頻繁に起こる。", "exKo": "빈번하게 일어난다."},
        {"word": "釈明", "reading": "しゃくめい", "meaning": "해명", "exJp": "理由を釈明する。", "exKo": "이유를 해명한다."},
        {"word": "巧妙", "reading": "こうみょう", "meaning": "교묘", "exJp": "巧妙な手口。", "exKo": "교묘한 수법."},
        {"word": "厳密", "reading": "げんみつ", "meaning": "엄밀", "exJp": "厳密な調査。", "exKo": "엄밀한 조사."},
        {"word": "執拗", "reading": "しつよう", "meaning": "집요", "exJp": "執拗に追いかける。", "exKo": "집요하게 뒤쫓다."}
    ]
}

js_content = "export const VOCAB_DATA = " + json.dumps(vocab_data, ensure_ascii=False, indent=4) + ";\n\nexport const ALL_WORDS = Object.values(VOCAB_DATA).flat();\n"
with open("c:\\Users\\kevin\\Desktop\\ai-japanese-app\\app-ui\\vocabData.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print("Vocab data explicitly expanded.")
